#!/usr/bin/env bash
# CT120 offline PseudoTCP SYN structural forensic.
#
# Compiles and executes a tiny local libnice PseudoTcpSocket harness.  The
# WritePacket callback does not send anything to the network; it only inspects
# the first packet generated by pseudo_tcp_socket_connect() and compares its
# public structural metadata with the first client PseudoTCP packet observed in
# both official Comelit Android captures.

set -u -o pipefail
umask 077

REPO=/root/comelit-door-diag-repo
REMOTE_REF=refs/remotes/origin/main
SOURCE_REL=safety-poc/research/media/v1/pseudotcp_local_syn_forensic.c
CT120_IP=192.168.1.85

FAIL=0

fail() {
    echo "$1"
    FAIL=1
}

if [ "${EUID}" -ne 0 ]; then
    echo "LOCAL_SYN_FORENSIC_REQUIRES_ROOT=true"
    exit 1
fi

for command in git cc pkg-config ip sha256sum grep; do
    if ! command -v "$command" >/dev/null 2>&1; then
        fail "LOCAL_SYN_FORENSIC_MISSING_COMMAND=$command"
    fi
done

if [ ! -d "$REPO/.git" ]; then
    fail "LOCAL_SYN_FORENSIC_REPO_PRESENT=false"
fi

if ! ip -4 addr show | grep -Fq "$CT120_IP/"; then
    fail "LOCAL_SYN_FORENSIC_CT120_IDENTITY=FAIL"
else
    echo "LOCAL_SYN_FORENSIC_CT120_IDENTITY=PASS"
fi

if ! git -C "$REPO" rev-parse --verify -q "$REMOTE_REF" >/dev/null 2>&1; then
    fail "LOCAL_SYN_FORENSIC_REMOTE_MAIN_PRESENT=false"
fi

REMOTE_MAIN=""
if [ "$FAIL" -eq 0 ]; then
    REMOTE_MAIN="$(git -C "$REPO" rev-parse "$REMOTE_REF")"
    echo "LOCAL_SYN_FORENSIC_REMOTE_MAIN=$REMOTE_MAIN"
fi

if ! pkg-config --exists nice glib-2.0 gobject-2.0; then
    fail "LOCAL_SYN_FORENSIC_BUILD_DEPS=FAIL"
else
    echo "LOCAL_SYN_FORENSIC_BUILD_DEPS=PASS"
    echo "LOCAL_SYN_FORENSIC_LIBNICE_VERSION=$(pkg-config --modversion nice)"
fi

if [ "$FAIL" -ne 0 ]; then
    echo "LOCAL_PSEUDOTCP_SYN_FORENSIC_RUNNER=FAIL_PREFLIGHT"
    echo "NETWORK_IO_PERFORMED=false"
    echo "HOME_ASSISTANT_TOUCHED=false"
    echo "DOOR_ACTION_SENT=false"
    echo "SELF_ACTIVATION_SENT=false"
    echo "MEDIA_SIGNALING_SENT=false"
    exit 1
fi

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
RUN_ROOT="/root/comelit-pseudotcp-local-syn-forensic-$STAMP"
SOURCE="$RUN_ROOT/pseudotcp_local_syn_forensic.c"
BINARY="$RUN_ROOT/pseudotcp_local_syn_forensic"
LOG="$RUN_ROOT/result.log"
mkdir -p "$RUN_ROOT"
chmod 700 "$RUN_ROOT"

git -C "$REPO" show "$REMOTE_MAIN:$SOURCE_REL" > "$SOURCE"
EXTRACT_RC=$?
echo "LOCAL_SYN_FORENSIC_SOURCE_EXTRACT_RC=$EXTRACT_RC"

if [ "$EXTRACT_RC" -ne 0 ]; then
    fail "LOCAL_SYN_FORENSIC_SOURCE_EXTRACT=FAIL"
else
    chmod 600 "$SOURCE"
    echo "LOCAL_SYN_FORENSIC_SOURCE_SHA256=$(sha256sum "$SOURCE" | awk '{print $1}')"
fi

if [ "$FAIL" -eq 0 ]; then
    cc \
      -O2 \
      -g \
      -Wall \
      -Wextra \
      -Werror \
      -o "$BINARY" \
      "$SOURCE" \
      $(pkg-config --cflags --libs nice glib-2.0 gobject-2.0) \
      2>"$RUN_ROOT/compile.stderr"
    BUILD_RC=$?
    cat "$RUN_ROOT/compile.stderr"
    echo "LOCAL_SYN_FORENSIC_BUILD_RC=$BUILD_RC"

    if [ "$BUILD_RC" -ne 0 ]; then
        fail "LOCAL_SYN_FORENSIC_BUILD=FAIL"
    fi
fi

if [ "$FAIL" -eq 0 ]; then
    chmod 700 "$BINARY"
    "$BINARY" 2>&1 | tee "$LOG"
    RUN_RC=${PIPESTATUS[0]}
    echo "LOCAL_SYN_FORENSIC_BINARY_RC=$RUN_RC"

    if [ "$RUN_RC" -ne 0 ]; then
        FAIL=1
    fi
fi

echo
echo "=== STRUCTURAL EXPECTATION FROM BOTH OFFICIAL CAPTURES ==="
echo "OFFICIAL_FIRST_CLIENT_WIRE_LEN=31"
echo "OFFICIAL_FIRST_CLIENT_SEQUENCE=0"
echo "OFFICIAL_FIRST_CLIENT_ACKNOWLEDGMENT=0"
echo "OFFICIAL_FIRST_CLIENT_CONTROL=0x00"
echo "OFFICIAL_FIRST_CLIENT_FLAGS=0x02"
echo "OFFICIAL_FIRST_CLIENT_DATA_LEN=7"
echo "OFFICIAL_RAW_PAYLOAD_EMITTED=false"

echo
echo "=== FINAL ==="
echo "LOCAL_SYN_FORENSIC_RUN_ROOT=$RUN_ROOT"
echo "NETWORK_IO_PERFORMED=false"
echo "HOME_ASSISTANT_TOUCHED=false"
echo "DOOR_ACTION_SENT=false"
echo "SELF_ACTIVATION_SENT=false"
echo "MEDIA_SIGNALING_SENT=false"

if [ "$FAIL" -eq 0 ]; then
    echo "LOCAL_PSEUDOTCP_SYN_FORENSIC_RUNNER=PASS"
    exit 0
fi

echo "LOCAL_PSEUDOTCP_SYN_FORENSIC_RUNNER=FAIL"
exit 1
